### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by utkarsh-var** [vikas-parashar/django-project-generator#1]
Update documentation, without sudo it won't work if the user is not root user, It should be
sudo pip install djauto
sudo djauto PROJECT_NAME APP_NAME

Otherwise it gives error on os.chdir(project_name) because it does not have root permission.

**Comment by vikas-parashar** [comment]
Thanks, I will mention that. Though, I was planning to suggest to use virtualenv for development. Please check Todos.

**Comment by vikas-parashar** [comment]
I've updated it. Feel free to contribute if you see any error in it.

**Comment by utkarsh-var** [comment]
yeah, sure.
